#include "grid.hpp"


void Grid::EPSDrawGrid(std::ostream& outFile, const int width, const int height, const int spacing) const
{
  outFile << "\n%Square grid\n"
          << "gs\n"
          << "0.75 setgray\n"
          << "2 TR\n"
          << "0.1 u div sl\n"
          << "\n"
          << spacing << " " << spacing << " " << width << "{\n"
          << "/i ed\n"
          << "i 1 m\n"
          << "gs\n"
          << "i 10 mod 0 eq {\n"
          << "i 3 string cvs sh\n"
          << "i " << height << " m i 3 string cvs sh\n"
          << "} if\n"
          << "gr\n"
          << "0 " << height - 2 << " rl\n"
          << "} for\n"
          << "\n"
          << spacing << " " << spacing << " " << height << "{\n"
          << "/i ed\n"
          << "1 i m\n"
          << "gs\n"
          << "i 10 mod 0 eq {\n"
          << "i 3 string cvs sh\n"
          << width << " i m i 3 string cvs sh\n"
          << "} if\n"
          << "gr\n"
          << width - 2 << " 0 rl\n"
          << "} for\n"
          << "\nst\n"
          << "gr\n"
          << "%---------------\n"
          << std::endl;
}
