name: BuildAndTest

on: #[push, pull_request]
  push:
    paths-ignore:
      - '*.md'
      - 'appveyor.yml'
      - '.gitlab-ci.yml'
      - '.travis.yml'
      - '.circleci/**'
      - 'docs/**'
      - 'data_files/**'
      - 'images/**'
      - 'scripts/**'

jobs:
  linux-build:
    name: Compilation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler: [clang++, g++]
        type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y cmake ninja-build clang gcc g++ clang

      - name: Configure
        run: cmake -GNinja -H. -B../Build -DINCH_UNITS_TEST=ON -DCMAKE_CXX_COMPILER=/usr/bin/${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.type }}

      - name: Build
        run: cmake --build ../Build

      - name: Test
        run: cd ../Build && ctest -j2 -V
