name: Windows

on: #[push, pull_request]
  push:
    paths-ignore:
      - '*.md'
      - '.gitlab-ci.yml'
      - '.circleci/**'
      - 'docs/**'
      - 'data_files/**'
      - 'images/**'
      - 'scripts/**'

jobs:
  windows-build:
    name: Compilation
    runs-on: windows-2022
    strategy:
      matrix:
        type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Configure
        run: cmake -Bbuild -DINCH_UNIT_TESTS=ON -DCMAKE_BUILD_TYPE=${{ matrix.type }}

      - name: Build
        run: cmake --build build --config ${{ matrix.type }} -j2

      - name: Test
        run: cd build && ctest -C ${{ matrix.type }} -j2 -V
